language: dart

dart:
  - 2.2.0
  - dev

dart_task:
- dartanalyzer: --fatal-infos --fatal-warnings .
- test

matrix:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.pub-cache
