include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_classes_with_only_static_members
    - avoid_dynamic_calls
    - avoid_returning_null
    - avoid_returning_this
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - comment_references
    - directives_ordering
    - invariant_booleans
    - join_return_with_assignment
    - literal_only_boolean_expressions
    - omit_local_variable_types
    - only_throw_errors
    - package_api_docs
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_statements
