name: timing
description: Timing is a simple package for tracking performance of both async and sync actions
version: 0.1.1+2
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/timing

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  json_annotation: '>=1.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.1.0
  pedantic: ^1.1.0
  test: ^1.0.0
